### ISSUE TITLE
Issue with connecting this stream to elasticsearch

### ISSUE THREAD

**Issue by akshaymhetre** [ippontech/spark-kafka-source#1]
Hi,

First of all, thanks for your blog and code, it's been really helpful.

I am using similar logic to create stream by storing offset and sending kafka messages to elasticsearch using EsSpark.saveJsonToEs API.

However, I am facing one issue if ES cluster is down this API will try to send this message to ES for sometime and then it will throw and exception and will fetch next message from the queue, and this will go on.  When ES cluster is up, we are not getting the earlier messages which was not sent as ES was down. 

Could you please help me with this ?

Thanks
Akshay

**Comment by aseigneurin** [comment]
This looks like an exception is being caught somewhere. I would say you need to let the exception go to Spark. The application will die and you can restart it later.

Could you show your code?

**Comment by akshaymhetre** [comment]
I don't want to stop the spark application, either streaming should pause or it should try to put same message again and again to ES till ES comes up or becomes reachable.

Here is the snippet of my code : 

`val topic = test1
val offsetsStore = new ZooKeeperOffsetsStore("localhost:2181", "/spark")

val messagesStream: DStream[(String, Array[OffsetRange])] = KafkaSource.getKafkaStream[String, String, StringDecoder, StringDecoder](ssc, kafkaParams, offsetsStore,topic)

 messagesStream.foreachRDD(rdd => {
    rdd.foreach(tup2 => {
      try{
        EsSpark.saveJsonToEs(ssc.sparkContext.parallelize(Seq(tup2._1)), "spark/logs")
        offsetsStore.saveOffsets(topic, tup2._2) // save offset only when message is successfully inserted
      }catch {
        case e:Exception => e.printStackTrace()  
      }
    })
  })`

**Comment by aseigneurin** [comment]
Well, you are obviously not calling the code I wrote since the method is called `KafkaSource.kafkaStream`, not `KafkaSource.getKafkaStream` and it returns a `DStream[(String, String)]`, not a `DStream[(String, Array[OffsetRange])].

If you do call the method correctly, the offsets are saved for you, i.e. you should **not** call `saveOffsets`.

Finally, as I suspected, you are catching an exception which is not the right way of doing things. You are just losing your data. Either implement some retry mechanism or let the application crash and restart later.

**Comment by akshaymhetre** [comment]
I have modified the KafkaSource.getKafkaStream so that it will return tuple (String, Array[OffsetRange]). As I wanted to save the offset to zookeeper after data is sent successfully to ES and not immediately after reading the stream. 

If I remove try catch block, it will crash the application.
